
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alex
 */
public class Vending1 extends javax.swing.JFrame {
    
    double totalPrice = 0;//the total price of the items
    static Item[] item = new Item[5];//selectable items
    static Item[] receiptItems = new Item[100];//an array to store the bought items(a max of 100 because each item has 20 units and there are 5 items)
    int indexSelected = 0;//the currently selected item's index (0-5)
    int j=0;

    /**
     * Creates new form Vending1
     */
    public Vending1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ItemSelect = new javax.swing.JComboBox<>();
        SelectedItem = new javax.swing.JLabel();
        CashAmount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TakeItems = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PayButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BuyItem = new javax.swing.JButton();
        ItemQuantity = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        QuantityBox = new javax.swing.JTextField();
        priceBox = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ItemSelect.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ItemSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chocolate", "Water", "Drink", "Snack", "Sweet" }));
        ItemSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemSelectActionPerformed(evt);
            }
        });

        SelectedItem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SelectedItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelectedItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CashAmount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CashAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashAmountActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Please select your item:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Please insert money:");

        TakeItems.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TakeItems.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("The Vending Machine V4.20");

        PayButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PayButton.setText("Pay");
        PayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Total Price:");

        BuyItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BuyItem.setText("Buy item");
        BuyItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyItemActionPerformed(evt);
            }
        });

        ItemQuantity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ItemQuantity.setText("Items left: 20");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Please enter the quantity");

        QuantityBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        QuantityBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityBoxActionPerformed(evt);
            }
        });

        priceBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(29, 29, 29)
                            .addComponent(ItemSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ItemQuantity)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BuyItem))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(SelectedItem, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CashAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(TakeItems, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(PayButton)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(priceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(QuantityBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(19, 19, 19)
                .addComponent(SelectedItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ItemSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(BuyItem)
                            .addComponent(ItemQuantity))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(QuantityBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CashAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PayButton))
                        .addGap(28, 28, 28)
                        .addComponent(TakeItems, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(priceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CashAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CashAmountActionPerformed

    private void PayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayButtonActionPerformed
        // TODO add your handling code here:
        
        if(Double.parseDouble(CashAmount.getText()) > totalPrice)//if the inserted cash amount is greater than the total price
        { 
            double change = Double.parseDouble(CashAmount.getText()) - totalPrice;//calculate the change
            TakeItems.setText("The change is: " + change);//show the change
            priceBox.setText("");
            FileWriter myWriter;
            try {
                myWriter = new FileWriter("Receipt.txt");
                myWriter.write("Your items are: \n");//print the receipt using a loop to add all the items
                for(int i = 0; i<j; i++)
                {
                    myWriter.write("1. " + (20 - receiptItems[i].quantity) + " * " + receiptItems[i].name + " price of" + receiptItems[i].price * (20 - receiptItems[i].quantity) + " \n");
                }
                myWriter.close();
            } catch (IOException ex) {
                Logger.getLogger(Vending1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(Double.parseDouble(CashAmount.getText()) == totalPrice)//if the inserted cash amount is equal to the price we just print the receipt
        {
            TakeItems.setText("Please take your items");//no change needed to be given
            priceBox.setText("");
            FileWriter myWriter;
            try {
                myWriter = new FileWriter("Receipt.txt");
                myWriter.write("Your items are: \n");
                for(int i = 0; i<j; i++)
                {
                    myWriter.write("1. " + (20 - receiptItems[i].quantity) + " * " + receiptItems[i].name + " with a price of " + receiptItems[i].price * (20 - receiptItems[i].quantity) + " \n");
                }
                myWriter.close();
                myWriter.close();
            } catch (IOException ex) {
                Logger.getLogger(Vending1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else //otherwise don't proceed with the purchase
        {
            TakeItems.setText("Not enough money!");
        }
        CashAmount.setText("");
    }//GEN-LAST:event_PayButtonActionPerformed

    private void BuyItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyItemActionPerformed
        // TODO add your handling code here:
        indexSelected = ItemSelect.getSelectedIndex();//get the selected item's index
        if(item[indexSelected].quantity - Double.parseDouble(QuantityBox.getText()) < 0)//if the selected quantity amount is bigger than the available quantity
        {   
            SelectedItem.setText("Not in stock right now");//item is not available
        }else //otherwise
        {
            totalPrice += item[indexSelected].price * Double.parseDouble(QuantityBox.getText());//add the price * selected quantity to the total price
            item[indexSelected].quantity-= Double.parseDouble(QuantityBox.getText());//lower quantity
            ItemQuantity.setText("Items left: " + String.valueOf(item[indexSelected].quantity));//display the number of items left
            SelectedItem.setText(item[indexSelected].name + " added to basket!");//announce that the item has been added
            priceBox.setText(String.valueOf(totalPrice));//update the total price
            receiptItems[j] = item[indexSelected];//add the purchased item to the receipt
            j++;
        }
        
    }//GEN-LAST:event_BuyItemActionPerformed

    private void ItemSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemSelectActionPerformed
        // TODO add your handling code here:
         ItemQuantity.setText("Items left: " + String.valueOf(item[indexSelected].quantity));//update the number of items left based on the selected item
    }//GEN-LAST:event_ItemSelectActionPerformed

    private void QuantityBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vending1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vending1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vending1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vending1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vending1().setVisible(true);
            }
        });
        for(int i = 0; i<5; i++)//initialise the item[] arrays
        {
            item[i] = new Item();
            receiptItems[i] = new Item();
            item[i].quantity = 20;
        }
        item[0].name = "Chocolate 2£"; item[0].price = 2;//initialising all the item's names and prices
        item[1].name = "Water 0.5£"; item[1].price = 0.5;
        item[2].name = "Drink 1£"; item[2].price = 1;
        item[3].name = "Snack 2£"; item[3].price = 2;
        item[4].name = "Sweet 1£"; item[4].price = 1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuyItem;
    private javax.swing.JTextField CashAmount;
    private javax.swing.JLabel ItemQuantity;
    private javax.swing.JComboBox<String> ItemSelect;
    private javax.swing.JButton PayButton;
    private javax.swing.JTextField QuantityBox;
    private javax.swing.JLabel SelectedItem;
    private javax.swing.JLabel TakeItems;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel priceBox;
    // End of variables declaration//GEN-END:variables
}
